version: '3'
services:
  ejbca:
    hostname: ejbca
    image : keyfactor/ejbca-ce
    ports : 
      - 80:8080
      - 443:8443
    volumes: 
      - ./data/ejbca:/mnt/persistent
    environment:
      - LOG_LEVEL_APP=INFO
      - LOG_LEVEL_SERVER=INFO
      - TLS_SETUP_ENABLED=true
  