version: '3'
services:
  nginx: 
    image : nginx:latest 
    ports : 
      - 80:80
      - 443:443
    volumes: 
      - ./data/leaf.pem:/etc/nginx/certs/server.pem
      - ./data/leaf.key:/etc/nginx/certs/server.key
      - ./nginx.conf:/etc/nginx/conf.d/default.conf