version: '3'
services:
  ejbca: 
    image : keyfactor/ejbca-ce
    ports : 
      - 80:8080
      - 443:8443
    environment:
      - TLS_SETUP_ENABLED="simple"
    volumes: 
      - ./data/ejbca:/mnt/persistent